### ISSUE TITLE
Multiple Nest thermostats / C to F

### ISSUE THREAD

**Issue by rhopkins7428** [aitormagan/nest_tracking#2]
Great work and directions, worked as expected first try!

I can see it polls multiple devices (smoke alarms/thermostats/etc) but only posts the first thermostat to influx
Would it be possible to post the temperatures under their respective device ID ?
Also maybe add an option for Fahrenheit instead of celsius?
I've attached a log file to show the values I'm referring.

Thanks for your work!

[nest_log.txt](https://github.com/aitormagan/nest_tracking/files/5146403/nest_log.txt)

**Comment by aitormagan** [comment]
I've updated the code in order to store the information of all your devices and not the first one. A influx tag is used to relate the measurement with the corresponding thermostat. 

Regarding to storing the data in Fahrenheit, I'm afraid the API is returning the info in Celsius so there is not a straight way. But you can store the info in Fahrenheit by modifying the `index.js` file and changing line 23 and applying Celsius to Fahrenheit formula:

```
                fields: { value: thermostat.device.current_temperature * 1,8 + 32 },
```
